[build]
  command = "npm run netlify-build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/build/manifest.json"]


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
